#!/bin/bash
# ===========================================================================
# time_synchronization_installer -- deploy and switch the time-synchronization
# role of a D-Robotics X5 board.
#
# Source file: time_synchronization_installer.sh.  It installs itself as the
# shorter command `timesync` (that is the name to type in the field, and the
# name used throughout the messages below); the file and the repository keep
# the long name.
#
# Written for mass production.  A freshly flashed board gets ONE command that
# installs everything and puts it in the requested role; the same tool switches
# an already-provisioned board between the two roles.
#
# The two roles are MUTUALLY EXCLUSIVE -- a board is either a slave or a
# master, never both, and switching rewrites every layer that differs:
#
#   slave   timesync slave
#           ptp4l as a slave; chrony stopped and disabled, because it would
#           fight ptp4l over CLOCK_REALTIME (two control loops steering one
#           clock).
#           Result: this board follows a PTP master on the network.
#
#   master  timesync master
#           ptp4l as a master + chrony (disciplines CLOCK_REALTIME from GNSS).
#           Result: this board serves its GNSS-disciplined time to the
#           network's slaves.
#
# WHICH CLOCK ALL OF THAT IS ABOUT is decided separately, by the time-stamping
# mode (--time-stamping, default software):
#
#   software / legacy   ptp4l stamps in CLOCK_REALTIME, so it disciplines that
#                       clock itself and no PTP hardware clock is involved.
#                       One daemon per role.
#   hardware            ptp4l stamps in the NIC's own clock, so it disciplines
#                       that, and phc2sys carries the time between the two
#                       (PHC -> CLOCK_REALTIME as a slave, the reverse as a
#                       master).  Two daemons per role.
#
# The role therefore lives in ONE generated file, /etc/default/ptp4l, which
# both systemd units read -- so switching never edits a unit and never
# enables/disables the units themselves.
#
# ---------------------------------------------------------------------------
# WHAT IT INSTALLS (all generated files carry a "generated by timesync" marker)
#
#   /etc/linuxptp/ptp4l-slave.conf        the slave role, complete
#   /etc/linuxptp/ptp4l-master.conf       the master role, complete (including
#                                         the GNSS time quality, if configured)
#   /etc/systemd/system/ptp4l@.service    shadows the packaged unit
#   /etc/systemd/system/phc2sys@.service  shadows the packaged unit (installed
#                                         always, enabled only in hardware mode)
#   /etc/default/ptp4l                    the role: args + interface
#   /usr/local/sbin/timesync              this script, for field switching
#   /etc/chrony/conf.d/20-ptp-refclock.conf copy of --refclock-file (master)
#   /var/lib/timesync/state               what was installed, by which version
#   /var/lib/timesync/disabled-ntp-units  NTP units we turned off, to restore
#
# ONE CONFIG FILE PER ROLE, NOT A SHARED ONE PLUS A ROLE ONE
#   ptp4l merges -f files by DISCARDING the earlier ones: with
#   `-f a -f b`, a key that only `a` sets is not in effect -- measured on this
#   board with `pmc 'GET DEFAULT_DATA_SET'` (a domainNumber set in the first
#   file read back as 0 from the running daemon).  Keys within ONE file do
#   accumulate, including across two [global] sections.  So each role gets a
#   single self-contained file, because the alternative silently ignores
#   whatever lands in the discarded one.
#
# WHY THE UNITS ARE REPLACED RATHER THAN OVERRIDDEN
#   The packaged phc2sys@.service declares Requires=ptp4l.service, but the
#   linuxptp package ships no such unit -- only the template ptp4l@.service.
#   phc2sys@eth0 therefore fails outright with "Unit ptp4l.service not found".
#   A drop-in cannot fix it: an empty "Requires=" was verified NOT to clear the
#   packaged list on systemd 249 (unlike Documentation=/ExecStart=, which
#   systemd documents as resettable).  A file in /etc/systemd/system shadows
#   the packaged one entirely, which does work.  Trade-off: a future linuxptp
#   package update to those units will not arrive -- if that matters, diff them
#   against /lib/systemd/system/ after an upgrade.
#
# EXIT CODES (stable; a production line may branch on them)
#   0  success
#   1  usage error (bad flag, bad value, contradictory flags)
#   2  preflight failed -- nothing was changed
#   3  apply failed (a file could not be written, a unit would not restart)
#   4  verify failed -- the unit is NOT fit to ship
#   5  GPS unconfigured: master was requested without a validated GNSS recipe
#
# ---------------------------------------------------------------------------
# TYPICAL USE
#
#   # new machine, fresh flash -- the slave role, one command.  This is
#   # software time stamping (the default): no PTP hardware clock is involved,
#   # accuracy is NTP-grade, and it works on any interface:
#   sudo ./time_synchronization_installer.sh install slave
#
#   # ... and the same, but taking its timestamps from the NIC's own clock
#   # (only where the NIC and its driver really do hardware-stamp):
#   sudo ./time_synchronization_installer.sh install slave --time-stamping hardware
#
#   # new machine, the master role, with a GNSS recipe validated on a bench unit:
#   sudo ./time_synchronization_installer.sh install master \
#        --refclock-file ./gnss/refclock.conf --gps-device /dev/ttyS0 \
#        --advertise-gnss-quality
#
#   # an already-provisioned board, in the field:
#   sudo timesync slave          # or: sudo timesync switch slave
#   sudo timesync master         # or: sudo timesync switch master
#   sudo timesync status
#   sudo timesync verify         # ship gate: exit 4 or 5 means DO NOT SHIP
#
#   # rehearse without touching the machine, then inspect what would be written:
#   sudo ./time_synchronization_installer.sh --dry-run install slave
#   ./time_synchronization_installer.sh --root /tmp/stage install slave \
#        && find /tmp/stage -type f
#
#   (1 and 2 are still accepted wherever a role is expected -- see the
#    "shorthands" note in --help.  The words are the interface.)
# ===========================================================================

set -euo pipefail

VERSION=1.1.0

# The one place the tool's names live.  NAME is the command an operator types
# and the prefix on every message; SRCFILE is how this file refers to itself in
# usage examples.  A rename should only ever mean editing these two lines --
# they feed the marker on every generated file, the install path and the state
# directory, so a half-done rename would leave files the tool no longer
# recognises as its own.
NAME=timesync
SRCFILE=time_synchronization_installer.sh
MARK="# generated by $NAME $VERSION -- DO NOT EDIT (rewritten by $NAME)"

DEFAULT_IFACE=eth0
DEFAULT_DOMAIN=0
DEFAULT_TRANSPORT=UDPv4
# ptp4l's own default is hardware.  This tool defaults to software because a NIC
# that advertises hardware timestamping is not the same thing as silicon that
# actually stamps the packets, and the difference is invisible until a master is
# on the wire -- see --time-stamping in the usage text.
DEFAULT_TIME_STAMPING=software

CONF_DIR=/etc/linuxptp
UNIT_DIR=/etc/systemd/system
ENV_FILE=/etc/default/ptp4l
STATE_DIR=/var/lib/$NAME
STATE_FILE=$STATE_DIR/state
DISABLED_NTP_FILE=$STATE_DIR/disabled-ntp-units
REFCLOCK_DEST=/etc/chrony/conf.d/20-ptp-refclock.conf
TOOL_DEST=/usr/local/sbin/$NAME

# Probed rather than hardcoded: this board has chrony.service and no
# chronyd.service; another machine may differ.
NTP_UNITS="chrony.service chronyd.service ntpd.service ntp.service systemd-timesyncd.service"
CHRONY_UNITS="chrony.service chronyd.service"

# ---------------------------------------------------------------------------
# Options
# ---------------------------------------------------------------------------
IFACE_OPT=""
DOMAIN=$DEFAULT_DOMAIN
TRANSPORT=$DEFAULT_TRANSPORT
TIME_STAMPING=$DEFAULT_TIME_STAMPING
DOMAIN_SET=0
TRANSPORT_SET=0
TIME_STAMPING_SET=0
REFCLOCK_FILE=""
GPS_DEVICE=""
ADVERTISE_GNSS=0
ADVERTISE_SET=0
# Set by do_switch: a switch is a role change, not a re-provision, so the GNSS
# side of the machine -- the recorded capability and the recipe file -- is left
# alone.  Read by write_state and write_install_files.
KEEP_GNSS=0
ROOT=""
DRY=0
FORCE=0
NO_APT=0
NO_VERIFY=0
CMD=""
ROLE_ARG=""
# Set by the `wait-iface` command, which is what the generated units call from
# ExecStartPre to close the MAC-up race (see do_wait_iface for the boot numbers).
WAIT_IFACE=""
WAIT_TIMEOUT=""

# Resolved during preflight
IFACE=""
ROLE=""
PTP4L_ARGS=""
PHC2SYS_ARGS=""
CHRONY_STATE=""
RESTART_NEEDED=0

TMPFILES=()

# ---------------------------------------------------------------------------
say()  { printf '%s: %s\n' "$NAME" "$*"; }
note() { printf '          %s\n' "$*"; }
warn() { printf '%s: WARNING: %s\n' "$NAME" "$*" >&2; }
die()  { local code="$1"; shift; printf '%s: ERROR: %s\n' "$NAME" "$*" >&2; exit "$code"; }

# Announcing something that is about to be DONE on the machine.  Under
# --dry-run it says so instead of implying the change happened.
act() { if [ "$DRY" = 1 ]; then say "would $*"; else say "$*"; fi; }

cleanup() { local f; for f in ${TMPFILES[@]+"${TMPFILES[@]}"}; do rm -f "$f"; done; }
on_signal() { cleanup; exit 130; }
trap cleanup EXIT
trap on_signal INT TERM

# Every path this tool touches goes through R(), so that --root can stage the
# whole tree somewhere harmless and let a human read it before it is deployed.
R() { printf '%s' "${ROOT}${1}"; }

usage() {
  cat >&2 <<'EOF'
usage: timesync <command> [options]

The two roles, and they are the only roles.  Either one runs ptp4l on its own,
and adds phc2sys only when --time-stamping hardware is in use:
  slave             Follow a PTP master on the network.  ptp4l runs as a slave
                    (slaveOnly, so it never takes over) and chrony is stopped
                    and disabled, because it would otherwise fight ptp4l over
                    CLOCK_REALTIME.
  master            Serve this board's time to the network, disciplined from
                    GNSS: ptp4l runs as a master, and chrony is enabled as the
                    time source.

commands
  install slave|master
                    Provision this machine for the given role and start it.
                    Converges: writes every config, unit and the switcher,
                    then restarts only what changed.  Safe to re-run; a second
                    run over an already-correct machine changes nothing.
  switch slave|master
                    Change the role of an ALREADY provisioned machine.  Refuses
                    if `install` has not been run on this machine yet.
                    Everything that is not the role carries over: the
                    interface, the domain and transport, and -- for a board
                    provisioned as a GNSS master -- the recipe file and the
                    GNSS time quality, so `switch master` brings the grandmaster
                    config back without the flags being repeated.  Only the
                    role-dependent files, the role file and chrony's state are
                    touched; the recipe is not, so a round trip is reversible.
                    Unlike `install`, one of these files being missing is not
                    a re-provision: a stale GNSS recipe is kept, not deleted.
  slave | master    Shorthands for `switch slave` / `switch master`.
  status            Configured role, live state of every piece, recent ptp4l
                    output, current system clock.  Changes nothing.
  verify [slave|master]
                    Ship gate for a production line.  Checks the role file, the
                    arguments the units will pass to each daemon, every unit
                    this time-stamping mode needs active AND enabled (and the
                    ones it does not need absent), the live argv of each
                    process, which clock ptp4l actually opened, and chrony's
                    state.  Changes nothing.
                    Exit 0 = fit to ship, 4 = failed a check, 5 = master with
                    no GNSS reference at all.  A unit that is down fails; a
                    unit that is up now but restarted earlier is only reported,
                    so a board that caught a transient boot-time restart is not
                    blocked from shipping.
  uninstall         Stop and remove everything this tool installed, and
                    re-enable the NTP units it had disabled.  The linuxptp
                    package itself is left in place.
  wait-iface IFACE [seconds]
                    Wait until IFACE is administratively up, then exit 0.  This
                    is the ExecStartPre of the generated units, not something
                    an operator normally runs: on a cold boot the NIC driver has
                    not yet opened the MAC when systemd starts the daemons, so
                    in hardware mode /dev/ptp0 is not openable yet ("Operation
                    not permitted") and in every mode there is no interface to
                    bind the PTP socket to.  Default timeout 30s; on timeout it
                    exits non-zero so the unit retries rather than starting a
                    daemon that cannot bind.
  -h | --help
  -V | --version

options
  --iface IFACE          Interface PTP runs on.  Default: the one recorded in
                         /etc/default/ptp4l, else the only interface on the
                         machine that can hardware-timestamp (in software mode,
                         with no such interface, the physical interface).
  --domain N             PTP domainNumber, 0-127 (default 0).
  --transport T          UDPv4 | UDPv6 | L2 (default UDPv4).
  --time-stamping MODE   software | hardware | legacy (default software).
                         Which clock ptp4l reads its timestamps from, and so
                         which clock it ends up disciplining:
                           software  the kernel stamps the packets, and the
                                     timestamp is taken in CLOCK_REALTIME, so
                                     ptp4l steers that clock itself.  No PTP
                                     hardware clock is involved and phc2sys is
                                     not installed.  Accuracy is bounded by
                                     interrupt and scheduling jitter -- tens of
                                     microseconds, i.e. NTP-grade.  Usable on
                                     any interface.
                           hardware  the NIC stamps the packet in its own clock
                                     (the PHC), which ptp4l therefore
                                     disciplines; phc2sys carries the time
                                     between that clock and CLOCK_REALTIME (PHC
                                     -> CLOCK_REALTIME as a slave, the reverse
                                     as a master).  Sub-microsecond, and the
                                     reason to run PTP at all -- but it requires
                                     silicon that really stamps, which
                                     `ethtool -T` advertising it does NOT prove.
                           legacy    the deprecated hardware-stamping interface.
                                     Still measured in CLOCK_REALTIME, so like
                                     software it needs no phc2sys, but it does
                                     require NIC support and most drivers have
                                     dropped it (this board's refuses it).
                         The mode is recorded and carried across `switch`; the
                         install record is the authority, and `verify` reports
                         what the running daemon actually bound.
  --refclock-file F      master: a chrony snippet describing this machine's
                         GNSS receiver (its refclock line, and a pps line if it
                         has one).  Installed as /etc/chrony/conf.d/
                         20-ptp-refclock.conf.  Validate one recipe on one
                         bench unit, review it, then deploy that same reviewed
                         file to the whole fleet.  Giving no recipe to
                         `install` removes any recipe installed earlier, so
                         what is on disk always matches the role just
                         installed; `switch` keeps it (see above).
  --gps-device DEV       master, required with --refclock-file: the device the
                         receiver is on (/dev/ttyS0, /dev/pps0, ...).  Its
                         existence is checked, and F must mention DEV -- this
                         catches a recipe pasted onto a differently wired unit.
  --advertise-gnss-quality
                         master, required with a GNSS recipe: have ptp4l
                         announce clockClass 6 / accuracy 0x21 / timeSource
                         GNSS.  Without it the slaves are told "not a
                         reference" and will not lock onto this master.
  --no-apt               Never call apt; fail the preflight instead if a
                         package is missing.
  --no-verify            Skip the post-install verify.  Exit 0 then means only
                         "the apply steps ran", not "the unit is fit to ship".
  --force                Override the checks that are judgement calls rather
                         than facts: a leftover ptp4l instance on another
                         interface, a --gps-device that does not exist yet, or
                         a `master` install with no GNSS recipe at all (a
                         skeleton -- `verify` will keep returning 5).
  --root DIR             Stage the generated tree under DIR instead of /.  apt,
                         systemctl and every hardware probe are skipped, so the
                         tree can be inspected on a laptop.  install and
                         uninstall only.
  --dry-run              Print every action, change nothing.

shorthands
  1 and 2                Accepted anywhere a role is expected, and mean exactly
                         `slave` and `master`.  The words are the interface;
                         the digits are kept only so an older note that says
                         "1" or "2" is still understood.  A bare `timesync 1`
                         is refused rather than treated as a switch, so a typo
                         cannot change the machine.
  -h | --help
  -V | --version
EOF
}

# ---------------------------------------------------------------------------
# Reading the generated files.  The values contain spaces ("-f a -f b"), so the
# file must NOT be sourced as shell; pull out the single line we want instead.
# Deliberately no pipe: under `set -o pipefail`, sed taking SIGPIPE from a
# `head -n1` would make the assignment itself fail under `set -e` and abort.
# ---------------------------------------------------------------------------
env_get() {  # env_get KEY -> value on stdout; exit 1 if unset or empty
  local v=""
  [ -r "$(R "$ENV_FILE")" ] || return 1
  v="$(sed -n "s/^$1=//p" "$(R "$ENV_FILE")")"
  v="${v%%$'\n'*}"
  [ -n "$v" ] || return 1
  printf '%s\n' "$v"
}

state_get() {  # state_get KEY -> value on stdout; exit 1 if absent
  local v=""
  [ -r "$(R "$STATE_FILE")" ] || return 1
  v="$(sed -n "s/^$1=//p" "$(R "$STATE_FILE")")"
  v="${v%%$'\n'*}"
  [ -n "$v" ] || return 1
  printf '%s\n' "$v"
}

conf_get() {  # conf_get CONF_PATH KEY -> value on stdout; exit 1 if absent
  local v=""
  [ -r "$(R "$1")" ] || return 1
  v="$(sed -n "s/^$2[[:space:]]*//p" "$(R "$1")")"
  v="${v%%$'\n'*}"
  [ -n "$v" ] || return 1
  printf '%s\n' "$v"
}

# Which clock this board's ptp4l stamps in.  The flag is what the units pass, so
# it is the effective setting on a running machine; an install predating
# --time-stamping has no flag, and ptp4l's own default of hardware is what such
# an install was really running.
stamping_in_use() {
  local args
  args=" $(env_get PTP4L_ARGS || true) "
  case "$args" in
    *' -S '*) printf 'software\n' ;;
    *' -L '*) printf 'legacy\n' ;;
    *' -H '*) printf 'hardware\n' ;;
    *)        printf 'hardware\n' ;;
  esac
}

# The install record is the authority -- a wrong flag in the env file has to be
# detectable, which it would not be if the expected arguments were derived from
# that same file.
stamping_recorded() {
  local v
  v="$(state_get time_stamping || true)"
  # Older installs predate the record, so fall back to the flag the units are
  # actually started with -- but only on a machine that has one.  On a bare
  # machine there is no answer at all, and printing one (hardware, the ptp4l
  # default) would describe a deployment that does not exist.
  if [ -z "$v" ] && [ -n "$(env_get PTP4L_ARGS || true)" ]; then
    v="$(stamping_in_use)"
  fi
  printf '%s\n' "$v"
}

# Is this unit actually *present* on this machine?  Ask systemd for LoadState
# rather than `systemctl cat`: cat succeeds for a unit that exists only as a
# dangling enable symlink (an alias left by an earlier run, or by a package
# that was removed without disabling it), and such a unit must be treated as
# absent -- there is nothing to start, and enabling it would silently do
# nothing while `timesync` reported success.
have_unit() { [ "$(systemctl show -p LoadState --value "$1" 2>/dev/null)" = loaded ]; }

unit_state() {  # "active/enabled"; never fails
  local a e
  a="$(systemctl is-active "$1" 2>/dev/null || true)"
  e="$(systemctl is-enabled "$1" 2>/dev/null || true)"
  printf '%s/%s\n' "${a:-n/a}" "${e:-n/a}"
}

# Any enabled ptp4l@/phc2sys@ instance other than the configured one.  Two
# instances on one machine fight over the same clock, so this is a fault.
#
# The instances are found on the filesystem, not through systemctl.  Both of
# the obvious queries lie about template instances on systemd 249, verified on
# the target: `list-unit-files 'ptp4l@*.service'` matches the *template* and
# reports it as "indirect", and `list-unit-files --state=enabled` filters the
# instances away entirely -- so an enabled ptp4l@usb0.service was invisible and
# the second-instance fault went undetected.  Enabling an instance IS the act
# of creating a symlink under <target>.wants/, so that symlink is the ground
# truth, and it is what `systemctl disable` removes.
enabled_instances() {
  local t u p dir
  for t in ptp4l phc2sys; do
    for dir in "$(R /etc/systemd/system)" "$(R /run/systemd/system)"; do
      for p in "$dir"/*.wants/"$t"@*.service; do
        [ -L "$p" ] || continue
        u="$(basename "$p")"
        [ "$u" != "$t@$IFACE.service" ] || continue
        printf '%s\n' "$u"
      done
    done
  done | sort -u
}

# ---------------------------------------------------------------------------
# Writing files.  Each install_* helper prints exactly one line saying whether
# anything changed -- so a second run over an already-converged machine visibly
# does nothing, which is what makes this safe to drive from a production script.
#
# The content is staged into a file in the DESTINATION directory and then moved
# into place, so a half-written config can never be observed, and the move
# stays atomic within one filesystem.
#
# Note the deliberate shape: the staging file is created and recorded here, in
# the top-level shell, and the template function is the only thing running on
# the left of a pipe.  Anything that records its own temp file from inside a
# pipeline (or a command substitution) would be recording it in a subshell, and
# the cleanup on exit would never see it.
# ---------------------------------------------------------------------------
CHANGED=0
TMPPATH=""

new_tmp() {  # new_tmp DEST_PATH -> sets TMPPATH
  local path
  path="$(R "$1")"
  if [ "$DRY" = 1 ]; then
    TMPPATH="$(mktemp)"
  else
    mkdir -p "$(dirname "$path")"
    TMPPATH="$(mktemp "${path}.tmp.XXXXXX")"
  fi
  TMPFILES+=("$TMPPATH")
}

install_bytes() {  # install_bytes TMP_FILE DEST_PATH [MODE]
  local tmp="$1" label="$2" mode="${3:-0644}" path
  path="$(R "$label")"

  if [ -e "$path" ] && cmp -s "$tmp" "$path"; then
    say "unchanged $label"
    rm -f "$tmp"
    return 0
  fi

  CHANGED=1
  if [ "$DRY" = 1 ]; then
    say "would write $label"
    rm -f "$tmp"
    return 0
  fi

  chmod "$mode" "$tmp"
  if [ -z "$ROOT" ]; then
    chown root:root "$tmp"
  fi
  mv -f "$tmp" "$path"
  say "wrote     $label"
}

install_tpl() {  # install_tpl TPL_FUNCTION DEST_PATH [MODE]
  new_tmp "$2"
  local tmp="$TMPPATH"
  "$1" | render >"$tmp"
  install_bytes "$tmp" "$2" "${3:-0644}"
}

# Same, but several templates concatenated into ONE file.  ptp4l reads its
# settings from the file named by -f and DISCARDS any earlier file on the same
# command line, so a role that needs "shared settings, plus mine, plus the GNSS
# block" has to arrive as one file rather than three -f arguments.
install_tpl_join() {  # install_tpl_join DEST_PATH TPL_FUNCTION...
  local dest="$1"; shift
  new_tmp "$dest"
  local tmp="$TMPPATH" f
  : >"$tmp"
  for f in "$@"; do
    "$f" | render >>"$tmp"
  done
  install_bytes "$tmp" "$dest"
}

install_from_file() {  # install_from_file SRC_FILE DEST_PATH [MODE]
  new_tmp "$2"
  local tmp="$TMPPATH"
  cat "$1" >"$tmp"
  install_bytes "$tmp" "$2" "${3:-0644}"
}

install_marked_copy() {  # install_marked_copy SRC_FILE DEST_PATH [MODE]
  new_tmp "$2"
  local tmp="$TMPPATH"
  { printf '%s\n' "$MARK"; cat "$1"; } >"$tmp"
  install_bytes "$tmp" "$2" "${3:-0644}"
}

remove_generated() {  # remove_generated PATH [SIGNATURE]
  # Only removes a file this tool wrote.  The signature defaults to the marker
  # every generated file carries as its first line; the installed copy of this
  # script cannot carry it (a shebang has to come first), so it is identified by
  # a phrase from its own header instead.  A file the operator owns must never
  # be removed just because it mentions timesync somewhere inside.
  local path sig="${2:-^# generated by $NAME}"
  path="$(R "$1")"
  [ -e "$path" ] || { say "absent    $1"; return 0; }
  if ! grep -q "$sig" "$path"; then
    warn "$1 does not look like a file timesync wrote; leaving it alone"
    return 0
  fi
  CHANGED=1
  if [ "$DRY" = 1 ]; then
    say "would remove $1"
  else
    rm -f "$path"
    say "removed   $1"
  fi
}

write_state() {
  local path prev gq
  path="$(R "$STATE_FILE")"
  prev="$(state_get installed || true)"
  # gnss_quality records a capability of the machine, not of the current role,
  # so a `switch` to slave keeps it -- that is what lets `switch master` bring back
  # the grandmaster config without the operator re-typing the recipe flags.
  # Only KEEP_GNSS (set by do_switch) does this: a plain `install` is
  # a full re-provision, and there the operator's flags are authoritative.
  # The state file has to be read before it is overwritten, hence reading it
  # here rather than in the callers.
  gq="$ADVERTISE_GNSS"
  if [ "$KEEP_GNSS" = 1 ] && [ "$ROLE" != master ]; then
    gq="$(state_get gnss_quality || true)"
    gq="${gq:-0}"
  fi
  if [ "$DRY" = 1 ]; then
    say "would write $STATE_FILE"
    return 0
  fi
  mkdir -p "$(dirname "$path")"
  cat >"$path" <<EOF
$MARK
# What was installed, by which version.  Read by 'timesync status'.
tool_version=$VERSION
role=$ROLE
iface=$IFACE
domain=$DOMAIN
transport=$TRANSPORT
time_stamping=$TIME_STAMPING
gnss_quality=$gq
installed=${prev:-$(date -Is)}
switched=$(date -Is)
EOF
  chmod 0644 "$path"
}

# The ledger of clock daemons this install turned off, so uninstall can put
# them back.  It leads with the marker line for the same reason every other
# generated file does: remove_generated() refuses to delete a file it does not
# recognise, and a ledger left behind would keep /var/lib/timesync/ alive after
# an uninstall.  Readers skip the marker (see do_uninstall).
record_disabled_ntp() {
  local path
  path="$(R "$DISABLED_NTP_FILE")"
  if [ "$DRY" = 1 ]; then
    say "would record disabled NTP unit $1"
    return 0
  fi
  mkdir -p "$(dirname "$path")"
  if [ ! -f "$path" ]; then
    printf '%s\n' "$MARK" >"$path"
  fi
  if ! grep -qxF "$1" "$path" 2>/dev/null; then
    printf '%s\n' "$1" >>"$path"
  fi
  chmod 0644 "$path"
}

# ===========================================================================
# The generated file contents.  @TOKENS@ inside these quoted heredocs are
# substituted by render(), which means the copies in this file are readable
# here -- an operator can review exactly what will land on the machine.
# ===========================================================================

tpl_common_conf() {
cat <<'PTPSVC_EOF'
@MARK@
#
# PTP settings for this board in ONE of its roles -- the settings both roles
# share, then the ones that role adds.  Why not a shared file plus a role file:
# ptp4l given two -f files DISCARDS the first, so a key set only there simply is
# not in effect.  Measured on this board with `pmc 'GET DEFAULT_DATA_SET'` (a
# domainNumber set in the first file read back as 0 from the running daemon).
# Both role files are kept up to date by `timesync install|switch`; only the one
# named in PTP4L_ARGS is read, and swapping roles swaps which one that is.
#
# The active file is named in PTP4L_ARGS in /etc/default/ptp4l, which is
# generated by `timesync install|switch`.  Do not hand-edit that file;
# `timesync install` rewrites it.
#
# The transport and domain below are the ones this board runs on, whatever its
# role.  To change them: `timesync install <role> --transport ... --domain ...`
# (or on a provisioned board, `timesync switch <role> --transport ...`).
#

[global]

network_transport   @TRANSPORT@
domainNumber        @DOMAIN@
delay_mechanism     E2E

# WHICH CLOCK ptp4l STAMPS IN, and therefore which clock it disciplines, is
# chosen on the command line (-S / -H / -L in PTP4L_ARGS in /etc/default/ptp4l)
# rather than here, deliberately: a value in this file can be silently
# discarded by a later -f file, the mode cannot afford to be, and the same flag
# is what an operator reads off `ps` when a clock is not being corrected.  The
# tool sets it from --time-stamping; see `timesync --help` for what the three
# modes do.
#
# Left at the packaged defaults on purpose:
#
#   twoStepFlag 1       as a slave we simply follow whichever mode the master
#                       announces (Sync, then Follow_Up carrying the stamp)
#   logging_level 6     INFO -- includes the once-per-second
#                       "master offset ... freq ... path delay ..." line
#   summary_interval 0  2^0 = one summary line per second
#   use_syslog 1        output goes to the journal: journalctl -u ptp4l@IFACE
PTPSVC_EOF
}

tpl_slave_conf() {
cat <<'PTPSVC_EOF'

# ===========================================================================
# Role: PTP SLAVE -- this board takes its time from a PTP master on the
# network.
#
# Companion daemons in this role:
#   chrony    stopped and disabled, because it would fight for CLOCK_REALTIME
#             (two control loops, one clock).  In `hardware` time stamping the
#             clock it fights over is phc2sys; in `software`/`legacy` it is
#             ptp4l itself.
#   phc2sys   only in `hardware` time stamping: it copies PHC ->
#             CLOCK_REALTIME, which is what makes `date` correct.  In
#             `software`/`legacy` ptp4l stamps in CLOCK_REALTIME directly, so
#             nothing is installed to copy anything.
#

[global]

# Never take over as master, even when no master is heard from.  Without this
# the board would fall back to serving its own free-running clock the moment
# the real master went quiet, and every other slave on the network would
# follow that bad time.
slaveOnly           1
PTPSVC_EOF
}

tpl_master_conf() {
cat <<'PTPSVC_EOF'

# ===========================================================================
# Role: PTP MASTER / grandmaster -- this board distributes GNSS time
# to the rest of the network.
#
# Companion daemons in this role:
#   chrony    disciplines CLOCK_REALTIME from the GNSS receiver
#   phc2sys   only in `hardware` time stamping: it copies CLOCK_REALTIME ->
#             PHC, so the NIC clock carries that time and ptp4l has something
#             worth advertising.  In `software`/`legacy` ptp4l stamps in
#             CLOCK_REALTIME itself, so there is nothing to copy.
#
# WITH NO TIME QUALITY SECTION BELOW THIS ROLE IS A SKELETON: the defaults
# (clockClass 248, clockAccuracy 0xFE) mean "not a reference", which tells every
# slave not to trust this clock as the root of the network.  The quality lines
# come from `timesync install master --advertise-gnss-quality`, and `timesync
# verify` refuses to pass until this board has both a GNSS reference and them.
#

[global]

slaveOnly           0
PTPSVC_EOF
}

tpl_grandmaster_conf() {
cat <<'PTPSVC_EOF'

# ===========================================================================
# Grandmaster time quality.  Present only in the master role, and only when
# `timesync install master --advertise-gnss-quality` (or the same flags on
# `switch`) was used.
#
# These three lines are what make this board's clock selectable as the root of
# the network.  They are only truthful when chrony is actually disciplined by a
# GNSS receiver, which is why they are added only once that has been arranged
# -- advertising a quality we do not have is worse than advertising none,
# because slaves would trust us.
#

[global]

# Values, then what they mean.  The meaning goes on its own comment line above:
# this ptp4l's config parser does not strip an inline trailing comment, it
# treats everything after the value as part of it -- so `clockClass 6  # ...`
# fails with "malformed value for option clockClass", ptp4l exits 254, and the
# unit restart-loops until the start limit gives up.
#
# clockClass 6 = locked to a primary reference
clockClass          6
# clockAccuracy 0x21 = within 100 ns
clockAccuracy       0x21
# timeSource 0x20 = GNSS
timeSource          0x20
PTPSVC_EOF
}

tpl_ptp4l_unit() {
cat <<'PTPSVC_EOF'
@MARK@
# Replaces the packaged /lib/systemd/system/ptp4l@.service.
#
# A unit file under /etc/systemd/system shadows the packaged one entirely --
# systemd takes the first match on its search path and does not merge the two --
# which is what is needed here: the packaged unit hardcodes the packaged config
# path and has no Restart=.  Trade-off: changes to the packaged unit in a future
# linuxptp package update will NOT arrive.  This file is short, so diff it
# against /lib/systemd/system/ptp4l@.service after an upgrade if that matters.
#
# The config comes from PTP4L_ARGS in /etc/default/ptp4l, which
# `timesync install|switch` generates.  PTP4L_ARGS is written unbraced on
# purpose: systemd splits an unbraced variable into separate arguments, which
# is how both -f flags get through.  ${PTP4L_ARGS} would arrive as a single
# argument and ptp4l would reject it.
#
# The interface still comes from %I, so the unit stays instance-generic
# (ptp4l@eth0.service).
[Unit]
Description=Precision Time Protocol (PTP) service for %I
Documentation=man:ptp4l
After=sys-subsystem-net-devices-%i.device
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
EnvironmentFile=/etc/default/ptp4l
# The NIC's PHC only becomes openable once the driver has opened the MAC; before
# that /dev/ptp0 fails with "Operation not permitted" and ptp4l dies at startup.
# `After=sys-subsystem-net-devices-%i.device` does not cover it -- that device
# unit goes active the moment the netdev is registered, seconds before the MAC
# is up -- and `After=network-online.target` did not either, because the
# NetworkManager wait-online helper is not enabled on this image, so that target
# is reached at t=0.  Hence an explicit gate.  See `timesync wait-iface` in the
# tool for the boot measurements.  It waits on IFF_UP, so a cable that is not
# plugged in does not block the unit.
#
# The gate is kept in every time-stamping mode, not just hardware: in software
# mode there is no PHC to open, but ptp4l still binds a UDP socket to the
# interface, and starting before the interface is up fails the same way.
ExecStartPre=/usr/local/sbin/timesync wait-iface %I
ExecStart=/usr/sbin/ptp4l $PTP4L_ARGS -i %I

# The packaged unit has no Restart and only orders after the network *device*,
# which exists before the interface has an address.  With UDPv4 transport
# ptp4l binds a socket on the interface, so an address-less eth0 makes it exit
# -- and with no Restart the service would sit dead until someone noticed.
# A deliberate `systemctl stop` exits 0 and is not restarted.
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
PTPSVC_EOF
}

tpl_phc2sys_unit() {
cat <<'PTPSVC_EOF'
@MARK@
# Replaces the packaged /lib/systemd/system/phc2sys@.service, which is broken:
# it declares
#
#     Requires=ptp4l.service
#     After=ptp4l.service
#
# for a unit this package does not ship -- only the template ptp4l@.service
# exists.  Starting phc2sys@eth0 therefore fails outright with
# "Unit ptp4l.service not found".  The correct, instance-matched dependency is
# ptp4l@%i.service, which with phc2sys@eth0.service expands to ptp4l@eth0.
#
# This is a replacement rather than a drop-in override because an empty
# `Requires=` in a drop-in does NOT clear the packaged one -- verified with
# `systemctl show phc2sys@eth0.service -p Requires` on this systemd 249, which
# still listed ptp4l.service.  The packaged dependency directives do not
# document an empty-string reset, unlike Environment=/ExecStart=/Documentation=.
#
# Same trade-off as ptp4l@.service: this file shadows the packaged unit, so
# package updates to that unit will not arrive.
[Unit]
Description=Synchronize system clock or PTP hardware clock (PHC)
Documentation=man:phc2sys
Requires=ptp4l@%i.service
After=ptp4l@%i.service
Before=time-sync.target

[Service]
Type=simple
EnvironmentFile=/etc/default/ptp4l
# Same MAC-up gate as ptp4l@.service, and it is needed here for a reason that is
# easy to get wrong: -w does NOT protect phc2sys from this race.  -w waits for
# ptp4l to report a synchronized state, but phc2sys resolves `-s eth0` to
# /dev/ptp0 while parsing its options, before any waiting happens -- on the boot
# measured in that comment it died at t=12.56s with the same
# "cannot open /dev/ptp0 for eth0: Operation not permitted", printing its usage.
ExecStartPre=/usr/local/sbin/timesync wait-iface %I
# -w holds phc2sys back until ptp4l reports a synchronized state, so it stays
# dormant -- and touches no clock -- while the master is absent or unreachable.
# That is what keeps this safe to leave running before a master exists.
ExecStart=/usr/sbin/phc2sys -w $PHC2SYS_ARGS
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
PTPSVC_EOF
}

tpl_env_file() {
cat <<'PTPSVC_EOF'
@MARK@
# Role selector for this board's PTP setup.
#
# `timesync` is the only thing that should write this file:
#
#     sudo timesync slave      # follow a PTP master on the network
#     sudo timesync master     # serve this board's own (GNSS) time to the network
#     sudo timesync status     # what is running right now
#
# The two systemd units read the arguments below, which is why switching roles
# needs neither a unit edit nor any enable/disable churn.  The PTP settings
# themselves live in /etc/linuxptp/.
#
# The two roles are mutually exclusive.  This file describes exactly one of
# them, and that is the only role that can be active at a time.
# ---------------------------------------------------------------------------

PTP_ROLE=@ROLE@
PTP_IFACE=@IFACE@

# ptp4l: the role's config file, plus the time-stamping mode as a flag.  The
# flag is here rather than in the config because a key in a config file can be
# silently discarded by a later -f file; this cannot.  -S software, -H hardware
# (NIC clock), -L legacy.
PTP4L_ARGS=@PTP4L_ARGS@

# phc2sys: -s is where time comes from, -c is where it is copied to.  The
# direction is what distinguishes the two roles.  Empty when the mode is
# software or legacy: ptp4l then stamps in CLOCK_REALTIME itself, so there is
# no second clock to carry time to or from and phc2sys is left disabled.
PHC2SYS_ARGS=@PHC2SYS_ARGS@
PTPSVC_EOF
}

render() {
  sed -e "s|@MARK@|$MARK|g" \
      -e "s|@TRANSPORT@|$TRANSPORT|g" \
      -e "s|@DOMAIN@|$DOMAIN|g" \
      -e "s|@IFACE@|$IFACE|g" \
      -e "s|@ROLE@|$ROLE|g" \
      -e "s|@PTP4L_ARGS@|$PTP4L_ARGS|g" \
      -e "s|@PHC2SYS_ARGS@|$PHC2SYS_ARGS|g"
}

# ===========================================================================
# The role
# ===========================================================================
# phc2sys exists to move time between the NIC's clock and CLOCK_REALTIME.  In
# `software` and `legacy` stamping there is no NIC clock in the loop -- ptp4l
# stamps in CLOCK_REALTIME and disciplines that clock itself -- so the unit is
# not installed at all.  Leaving it running there is worse than useless: it
# would copy a free-running PHC into the very clock ptp4l is disciplining.
uses_phc2sys() { [ "$TIME_STAMPING" = hardware ]; }

# The flag that selects the mode, as an argument to ptp4l.  Deliberately on the
# command line and not in the config file: an -f file read after another one
# discards it (see the file header), so a config-file setting can be silently
# lost, whereas this cannot.
stamping_flag() {
  case "$TIME_STAMPING" in
    software) printf '%s\n' -S ;;
    legacy)   printf '%s\n' -L ;;
    *)        printf '%s\n' -H ;;
  esac
}

role_values() {  # slave | master -> ROLE, args, chrony state
  case "$1" in
    slave)
      ROLE=slave
      PTP4L_ARGS="-f $CONF_DIR/ptp4l-slave.conf"
      PHC2SYS_ARGS="-s ${IFACE} -c CLOCK_REALTIME"
      CHRONY_STATE=disabled
      ;;
    master)
      ROLE=master
      PTP4L_ARGS="-f $CONF_DIR/ptp4l-master.conf"
      PHC2SYS_ARGS="-s CLOCK_REALTIME -c ${IFACE}"
      CHRONY_STATE=enabled
      ;;
    *)
      die 1 "unknown role '$1' (want: slave | master)"
      ;;
  esac
  PTP4L_ARGS="$PTP4L_ARGS $(stamping_flag)"
  if ! uses_phc2sys; then
    PHC2SYS_ARGS=""
  fi
}

# Is a GNSS recipe available -- either one being installed right now, or one
# already on the machine from an earlier install?
gps_ready() {
  [ -n "$REFCLOCK_FILE" ] || [ -s "$(R "$REFCLOCK_DEST")" ]
}

# ===========================================================================
# Preflight.  preflight_args is pure argument checking and runs for every
# command; preflight_machine is skipped under --root, because there is no
# machine.
# ===========================================================================
preflight_args() {
  case "$DOMAIN" in
    ''|*[!0-9]*) die 1 "--domain must be a number, got '$DOMAIN'" ;;
  esac
  if [ "$DOMAIN" -gt 127 ]; then
    die 1 "--domain must be 0-127 (IEEE 1588), got '$DOMAIN'"
  fi

  case "$TRANSPORT" in
    UDPv4|UDPv6|L2) ;;
    *) die 1 "--transport must be UDPv4, UDPv6 or L2, got '$TRANSPORT'" ;;
  esac

  case "$TIME_STAMPING" in
    software|hardware|legacy) ;;
    *) die 1 "--time-stamping must be software, hardware or legacy, got '$TIME_STAMPING'" ;;
  esac

  if [ -n "$IFACE_OPT" ]; then
    case "$IFACE_OPT" in
      '.'|'..'|*[!A-Za-z0-9_.:-]*) die 1 "--iface '$IFACE_OPT' is not a valid interface name" ;;
    esac
  fi

  if [ -n "$GPS_DEVICE" ] && [ -z "$REFCLOCK_FILE" ]; then
    die 1 "--gps-device only means something together with --refclock-file (the recipe is what names the device)"
  fi

  if [ -n "$REFCLOCK_FILE" ]; then
    # A GNSS reference exists in order to be distributed, so it has no meaning
    # in the role that consumes somebody else's time.
    if [ "$ROLE" = slave ]; then
      die 1 "--refclock-file is only meaningful for the master role (that board serves GNSS time), not for slave"
    fi
    [ -r "$REFCLOCK_FILE" ] || die 2 "--refclock-file '$REFCLOCK_FILE' is not readable"
    [ -s "$REFCLOCK_FILE" ] || die 2 "--refclock-file '$REFCLOCK_FILE' is empty"
    if ! grep -qE '^[[:space:]]*refclock[[:space:]]' "$REFCLOCK_FILE"; then
      die 2 "--refclock-file '$REFCLOCK_FILE' has no 'refclock' line, so chrony would never use the receiver"
    fi
    [ -n "$GPS_DEVICE" ] || die 1 "--gps-device is required with --refclock-file: it is what ties the recipe to this machine's wiring"
    if ! grep -qF -- "$GPS_DEVICE" "$REFCLOCK_FILE"; then
      die 2 "--refclock-file never mentions '$GPS_DEVICE'; a recipe written for a differently wired unit is the classic fleet-wide mistake"
    fi
  fi

  if [ "$ADVERTISE_GNSS" = 1 ]; then
    if [ "$ROLE" != master ]; then
      die 1 "--advertise-gnss-quality is for the master role only"
    fi
    # Announcing a reference we do not have is strictly worse than announcing
    # none, because slaves would trust us.
    gps_ready || die 1 "--advertise-gnss-quality with no GNSS recipe on this machine would advertise a reference this board does not have"
  fi

  if [ "$ROLE" = master ] && ! gps_ready && [ "$FORCE" != 1 ]; then
    die 5 "the master role needs a GNSS recipe: pass --refclock-file F --gps-device D --advertise-gnss-quality, or --force to install the GPS-less skeleton (verify will keep reporting 5)"
  fi
}

apt_ensure() {
  local missing=() m
  command -v ptp4l >/dev/null 2>&1 || [ -x /usr/sbin/ptp4l ] || missing+=(linuxptp)
  command -v ethtool >/dev/null 2>&1 || [ -x /usr/sbin/ethtool ] || missing+=(ethtool)
  [ ${#missing[@]} -gt 0 ] || return 0

  if [ "$NO_APT" = 1 ]; then
    die 2 "missing packages: ${missing[*]} (and --no-apt was given)"
  fi
  if [ "$DRY" = 1 ]; then
    say "would install: ${missing[*]}"
    return 0
  fi

  say "installing: ${missing[*]}"
  if ! DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends "${missing[@]}"; then
    die 2 "apt-get install ${missing[*]} failed -- if the package lists are stale, run 'apt-get update' and retry"
  fi
  for m in "${missing[@]}"; do
    case "$m" in
      linuxptp) command -v ptp4l >/dev/null 2>&1 || [ -x /usr/sbin/ptp4l ] || die 2 "ptp4l still missing after apt-get install linuxptp" ;;
      ethtool)  command -v ethtool >/dev/null 2>&1 || [ -x /usr/sbin/ethtool ] || die 2 "ethtool still missing after apt-get install ethtool" ;;
    esac
  done
}

# Interfaces to guess among.  Only a NIC that timestamps in hardware can carry
# PTP at NIC accuracy, so with `hardware`/`legacy` stamping those are the only
# ones worth guessing among.  With `software` the NIC's clock is out of the
# picture entirely, so any interface will do (argument `physical` lists the ones
# that are real NICs rather than virtual links).
iface_candidates() {  # [physical]
  local i caps
  for i in /sys/class/net/*; do
    i="${i##*/}"
    [ "$i" != lo ] || continue
    if [ "${1:-}" = physical ]; then
      [ -e "/sys/class/net/$i/device" ] || continue
      printf '%s\n' "$i"
      continue
    fi
    caps="$(ethtool -T "$i" 2>/dev/null || true)"
    case "$caps" in
      *hardware-transmit*hardware-receive*|*hardware-receive*hardware-transmit*) printf '%s\n' "$i" ;;
    esac
  done
}

resolve_iface() {
  if [ -n "$IFACE_OPT" ]; then
    IFACE="$IFACE_OPT"
    return 0
  fi

  local recorded
  recorded="$(env_get PTP_IFACE || true)"
  if [ -n "$recorded" ]; then
    IFACE="$recorded"
    note "interface from the existing $ENV_FILE: $IFACE"
    return 0
  fi

  if [ -n "$ROOT" ]; then
    IFACE="$DEFAULT_IFACE"
    note "--root: no interface recorded, staging for $IFACE (pass --iface to change)"
    return 0
  fi

  local cands n basis="timestamps in hardware"
  cands="$(iface_candidates)"
  n="$(printf '%s\n' "$cands" | grep -c . || true)"
  if [ "$n" = 0 ] && [ "$TIME_STAMPING" = software ]; then
    # Nothing here timestamps in hardware, which stopped the old version of
    # this tool dead.  It is not a stop in software mode: the kernel stamps the
    # packets, so any interface carries PTP, and a real NIC is still the better
    # guess than a virtual link.
    cands="$(iface_candidates physical)"
    n="$(printf '%s\n' "$cands" | grep -c . || true)"
    basis="is a physical interface"
  fi
  case "$n" in
    1)
      IFACE="$cands"
      note "only interface that $basis: $IFACE"
      ;;
    0)
      if [ "$TIME_STAMPING" = software ]; then
        die 2 "no interface found to run PTP on -- pass --iface"
      fi
      die 2 "no interface on this machine can hardware timestamp, which --time-stamping $TIME_STAMPING needs; use --time-stamping software to run on any interface, or pass --iface"
      ;;
    *)
      die 2 "several interfaces could carry PTP:$(printf ' %s' $cands) -- pass --iface to choose"
      ;;
  esac
}

# ---------------------------------------------------------------------------
# Block until the interface's MAC has been brought up, then return.
#
# This exists for one specific, reproducible boot race on the X5, and it is the
# ExecStartPre of both units.  A NIC's PHC is readable only once its driver has
# opened the MAC.  Before that, /dev/ptp0 exists and opens fail with
#
#     hobot_gmac ... eth0: eth_ptp_get_time, device has not been brought up
#     failed to open /dev/ptp0: Operation not permitted
#
# Measured on a cold boot (2026-09-16 17:52, boot_id 0d71b03b):
#
#     t=12.52s  ptp4l   selected /dev/ptp0, then died: Operation not permitted
#     t=12.56s  phc2sys same error, died before it ever reached its -w wait
#     t=13.36s  driver opens the MAC (PHY probe)
#     t=18.13s  ptp4l's automatic restart happened to land after the MAC was up
#
# Two things follow.  First, phc2sys is NOT protected by its own -w: it resolves
# `-s eth0` to /dev/ptp0 while parsing its options, before waiting for ptp4l,
# so it needs this gate just as much.  Second, both units survived only because
# Restart=on-failure retried 5s later -- which is luck, not provisioning: the
# window is however long the driver takes, and a retry landing inside it just
# burns another attempt and leaves a scary journal on a board that is otherwise
# perfectly healthy.  Production line sees a failed-then-recovered unit.
#
# The hard gate is IFF_UP (administratively up), not carrier.  IFF_UP is set as
# soon as the driver's ndo_open returns, which is precisely the condition the
# driver is asking about.  It is set even with no cable in the port, so the gate
# can never wedge a unit that is merely unplugged -- whereas *requiring* carrier
# would refuse to start PTP until someone plugged a master in, the opposite of
# what the slave role is for (run now, lock whenever a master appears).
#
# On timeout the gate exits non-zero, deliberately: the unit then fails and
# systemd retries, rather than bringing up a daemon we already know cannot open
# the PHC.
#
# IFF_UP is necessary but it is not the whole story, because it arrives well
# before carrier -- measured on the boot above: MAC open at ~13.4s, carrier at
# ~16.65s.  Starting inside that window makes ptp4l's port go FAULTY on
# "link down" and print
#
#     port 1: assuming the grand master role
#     port 1: master state recommended in slave only mode
#     port 1: defaultDS.priority1 probably misconfigured
#
# On a slave-only board that reads like the board is trying to serve time to the
# network.  It is not -- slaveOnly suppresses the takeover, and the port returns
# to LISTENING the instant the link comes up -- but during those seconds the
# port is FAULTY, i.e. it is not listening, so it cannot hear the master's SYNC.
# A wired board therefore both looks alarming and locks later than it needs to.
#
# So after the gate, a short, BOUNDED, BEST-EFFORT wait for carrier:
#
#   bounded     a board with nothing plugged in must still come up armed, so
#               this gives up after CARRIER_GRACE and starts anyway
#   best-effort  never fails -- a link that is down is a normal condition that
#               ptp4l handles by design, so it is not this tool's place to
#               refuse over it
#
# Quiet on success: this runs from ExecStartPre, and systemd puts its stdout in
# the journal, so a line here would be a line on every boot for no reason.
# ---------------------------------------------------------------------------
CARRIER_GRACE=5      # seconds; see above

carrier_up() {
  local c
  c="$(cat "/sys/class/net/$1/carrier" 2>/dev/null || true)"
  [ "$c" = 1 ]
}

do_wait_iface() {
  local iface="${1:-}" limit="${2:-30}" ticks flags path warned=0 up=0

  [ -n "$iface" ] || die 1 "wait-iface needs an interface name"
  case "$limit" in '' | *[!0-9]*) die 1 "wait-iface: timeout must be a whole number of seconds, got '$limit'" ;; esac
  path="/sys/class/net/$iface/flags"

  # Phase 1 -- the hard gate.  0.2s granularity; costs 5 sysfs reads a second
  # and only ever spins while the interface is still coming up, because a board
  # that has already booted satisfies this on the first iteration.
  ticks=$((limit * 5))
  while [ "$ticks" -gt 0 ]; do
    if [ -r "$path" ]; then
      flags="$(cat "$path" 2>/dev/null || printf '0')"
      # sysfs prints the flags as a 0x-prefixed hex literal, which $(( )) reads
      # natively.  IFF_UP is bit 0.  The `case` exists to tell "not up yet"
      # apart from "we do not understand this file": masking a decimal string
      # in $(( )) would silently mean something else, so an unknown format is
      # called out once rather than being mistaken for a real answer.
      case "$flags" in
        0x* | 0X*)
          # `if`, not `[ ... ] && up=1`: a bare `&&` list that comes out false
          # is a non-zero command to `set -e`, which would abort the function on
          # the very first not-yet-up iteration.
          if [ $((flags & 1)) -eq 1 ]; then up=1; break; fi
          ;;
        *)
          if [ "$warned" = 0 ]; then
            warned=1
            note "unexpected flag format '$flags' from $path; still waiting for IFF_UP"
          fi
          ;;
      esac
    fi
    sleep 0.2
    ticks=$((ticks - 1))
  done

  if [ "$up" -ne 1 ]; then
    printf '%s: ERROR: %s is not up after %ss -- refusing to start a daemon on an interface that does not exist yet (ptp4l would have no socket to bind, and in hardware mode no PHC to open either)\n' \
      "$NAME" "$iface" "$limit" >&2
    return 1
  fi

  # Phase 2 -- the bounded, best-effort carrier grace.  Never fails and never
  # blocks past CARRIER_GRACE, so an unplugged board still comes up armed.
  ticks=0
  while [ "$ticks" -lt $((CARRIER_GRACE * 5)) ]; do
    if carrier_up "$iface"; then break; fi
    sleep 0.2
    ticks=$((ticks + 1))
  done
  return 0
}

preflight_machine() {
  if [ "$DRY" != 1 ]; then
    [ "$(id -u)" -eq 0 ] || die 2 "must run as root (try: sudo $0 $*)"
  fi

  command -v systemctl >/dev/null 2>&1 || die 2 "systemd is required (no systemctl on PATH)"
  [ -d /sys/class/net ] || die 2 "/sys/class/net is missing -- this does not look like a Linux box we can configure"

  [ -n "$IFACE" ] || die 2 "no interface resolved; pass --iface"
  [ -d "/sys/class/net/$IFACE" ] || die 2 "interface '$IFACE' does not exist on this machine"

  local caps phc
  caps="$(ethtool -T "$IFACE" 2>/dev/null || true)"
  if [ "$TIME_STAMPING" = software ]; then
    # The kernel takes the stamp in CLOCK_REALTIME, so nothing about the NIC's
    # own clock is relevant here and there is no capability to require.  What
    # the NIC reports is still worth printing, because "ethtool -T advertises
    # hardware timestamping" is often why a board was assumed to be a hardware
    # candidate -- and advertising is not the same as stamping.
    case "$caps" in
      *hardware-transmit*) note "time stamping: software (the NIC also advertises hardware timestamping; that is not proof it works)" ;;
      *)                   note "time stamping: software (the NIC does not advertise hardware timestamping)" ;;
    esac
  else
    [ -n "$caps" ] || die 2 "ethtool -T $IFACE returned nothing; cannot confirm hardware timestamping"
    case "$caps" in
      *hardware-transmit*) ;;
      *) die 2 "$IFACE cannot hardware-transmit timestamps, which --time-stamping $TIME_STAMPING needs; use --time-stamping software instead (or --iface IFACE for another interface)" ;;
    esac
    case "$caps" in
      *hardware-receive*) ;;
      *) die 2 "$IFACE cannot hardware-receive timestamps, which --time-stamping $TIME_STAMPING needs; use --time-stamping software instead (or --iface IFACE for another interface)" ;;
    esac
    phc="$(printf '%s\n' "$caps" | sed -n 's/^PTP Hardware Clock: *//p')"
    [ -n "$phc" ] || die 2 "$IFACE exposes no PTP hardware clock, so --time-stamping $TIME_STAMPING has no clock to discipline; use --time-stamping software instead"
    note "time stamping: $TIME_STAMPING; PTP hardware clock: /dev/ptp$phc"
  fi

  # A locally administered MAC (U/L bit set) is regenerated on every boot on
  # this hardware, which changes this board's grandmasterIdentity.  That does
  # not stop time synchronisation working: the slaves treat the new identity as
  # a new master and re-lock, once, per reboot.  So this is reported and never
  # a gate -- a board whose MAC is regenerated is still a working grandmaster,
  # and refusing to install it would block a deployment over an operational
  # nuisance rather than a fault.
  if [ "$ROLE" = master ]; then
    local mac b
    mac="$(cat "/sys/class/net/$IFACE/address" 2>/dev/null || true)"
    if [ -n "$mac" ]; then
      b="$((16#${mac%%:*}))"
      if [ $((b & 2)) -ne 0 ]; then
        warn "$IFACE MAC $mac is locally administered, so it is regenerated on every boot and the slaves will re-lock once per reboot.  Time sync still runs; fix it at provisioning by pinning the MAC if that re-lock matters"
      else
        note "MAC $mac is globally unique, so grandmasterIdentity is stable across reboots"
      fi
    fi
  fi

  # A second PTP instance would fight this one for the same clock.  Refuse
  # rather than silently disabling something an operator may have set up.
  local found u
  found="$(enabled_instances | tr '\n' ' ')"
  if [ -n "${found// /}" ]; then
    if [ "$FORCE" != 1 ]; then
      die 2 "other PTP instances are enabled: $found-- two instances would fight over the same clock; disable them, or pass --force to let this tool disable them"
    fi
    for u in $found; do
      warn "disabling leftover instance $u"
      if [ "$DRY" != 1 ]; then systemctl disable --now "$u" >/dev/null 2>&1 || true; fi
    done
  fi

  if [ -n "$GPS_DEVICE" ] && [ "$ROLE" = master ]; then
    if [ ! -e "$GPS_DEVICE" ]; then
      if [ "$FORCE" != 1 ]; then
        die 2 "--gps-device $GPS_DEVICE does not exist on this machine; the recipe probably belongs to a differently wired unit (pass --force if the port appears later)"
      fi
      warn "--gps-device $GPS_DEVICE does not exist yet (--force)"
    else
      note "GNSS device present: $GPS_DEVICE"
    fi
  fi
}

# ===========================================================================
# Applying the role.  chrony first, then the role file, then the units; the
# order differs per role on purpose -- see the comment inside.
# ===========================================================================
set_chrony_state() {
  # any / chrony_done: the chrony units are aliases of one daemon on Debian
  # (chrony.service, chronyd.service).  Only the first one found is driven, so
  # a machine carrying both names does not get two enable/start pairs -- and so
  # `verify`, which reads any/all of the names, still agrees with what was done.
  local u any=0 chrony_done=0
  for u in $NTP_UNITS; do
    have_unit "$u" || continue
    if [ "$CHRONY_STATE" = enabled ]; then
      case " $CHRONY_UNITS " in
        *" $u "*) ;;
        *) continue ;;
      esac
      [ "$chrony_done" = 0 ] || continue
      chrony_done=1
      # master role: chrony is this board's time source, so it must be UP first
      # -- phc2sys should copy an already-disciplined clock, not chase one that
      # is still stepping.
      any=1
      if [ "$(systemctl is-enabled "$u" 2>/dev/null || true)" != enabled ]; then
        act "enable $u"
        if [ "$DRY" != 1 ]; then systemctl enable "$u" >/dev/null 2>&1 || true; fi
      fi
      if [ "$(systemctl is-active "$u" 2>/dev/null || true)" != active ]; then
        act "start $u"
        if [ "$DRY" != 1 ]; then systemctl start "$u" >/dev/null 2>&1 || true; fi
      fi
    else
      # slave role: phc2sys owns CLOCK_REALTIME, so every other clock daemon
      # must be gone -- stopped BEFORE phc2sys starts, or the clock briefly has
      # two masters correcting it in different directions.
      local a e
      a="$(systemctl is-active "$u" 2>/dev/null || true)"
      e="$(systemctl is-enabled "$u" 2>/dev/null || true)"
      [ "$a" = active ] || [ "$e" = enabled ] || continue
      act "disable $u (it would fight phc2sys over CLOCK_REALTIME)"
      if [ "$e" = enabled ]; then
        record_disabled_ntp "$u"
      fi
      if [ "$DRY" != 1 ]; then systemctl disable --now "$u" >/dev/null 2>&1 || true; fi
    fi
  done
  if [ "$CHRONY_STATE" = enabled ] && [ "$any" != 1 ]; then
    warn "no chrony unit found; the master role needs chrony to discipline the clock from GNSS"
  fi
}

apply_role() {
  local u4l="ptp4l@${IFACE}.service" uc2s="phc2sys@${IFACE}.service"
  local need_restart="$RESTART_NEEDED" u a
  local units=("$u4l")

  if uses_phc2sys; then
    units+=("$uc2s")
  fi

  set_chrony_state

  CHANGED=0
  install_tpl tpl_env_file "$ENV_FILE"
  if [ "$CHANGED" = 1 ]; then
    need_restart=1
  fi

  for u in "${units[@]}"; do
    if ! systemctl is-enabled "$u" >/dev/null 2>&1; then
      act "enable $u (so the role survives a reboot)"
      if [ "$DRY" != 1 ]; then systemctl enable "$u" >/dev/null 2>&1 || true; fi
      need_restart=1
    fi
  done

  # Leaving a phc2sys behind after switching to software/legacy stamping would
  # be worse than untidy: it copies a free-running PHC into CLOCK_REALTIME,
  # which is exactly the clock ptp4l now disciplines, so the two would pull
  # against each other.  Not enabling it is not enough -- the previous install
  # enabled it, and that survives until it is disabled.
  if ! uses_phc2sys && have_unit "$uc2s"; then
    a="$(systemctl is-active "$uc2s" 2>/dev/null || true)"
    if [ "$a" = active ] || [ "$(systemctl is-enabled "$uc2s" 2>/dev/null || true)" = enabled ]; then
      act "disable $uc2s (time stamping is $TIME_STAMPING: there is no second clock for it to copy)"
      if [ "$DRY" != 1 ]; then systemctl disable --now "$uc2s" >/dev/null 2>&1 || true; fi
    fi
    # `disable --now` on a phc2sys still inside its `-w` wait (which is where it
    # sits whenever ptp4l has no master yet) kills it mid-wait and systemd
    # records that as exit 254 -- "failed".  A board that is correctly running
    # software stamping should not show up in `systemctl --failed` on the line,
    # so clear the record.  Safe when nothing failed: reset-failed on a healthy
    # unit is a no-op.
    if [ "$DRY" != 1 ] && [ "$(systemctl is-failed "$uc2s" 2>/dev/null || true)" = failed ]; then
      systemctl reset-failed "$uc2s" >/dev/null 2>&1 || true
    fi
  fi

  if [ "$need_restart" = 1 ]; then
    act "restart ${units[*]}"
    if [ "$DRY" != 1 ]; then
      systemctl restart "${units[@]}" || die 3 "units failed to restart -- inspect: journalctl -u $u4l -n 50"
    fi
  else
    for u in "${units[@]}"; do
      a="$(systemctl is-active "$u" 2>/dev/null || true)"
      if [ "$a" != active ]; then
        act "start $u"
        if [ "$DRY" != 1 ]; then systemctl start "$u" >/dev/null 2>&1 || true; fi
      fi
    done
    say "already in role $ROLE on $IFACE; nothing needed restarting"
  fi

  printf '\n'
  say "role set to $ROLE on $IFACE (chrony $CHRONY_STATE, time stamping $TIME_STAMPING)"
  note "${units[*]} enabled, so this survives a reboot"
  note "run \"$NAME status\" for the live state"
}

# ===========================================================================
# Verify -- the ship gate.  It checks what this tool controls, and deliberately
# does NOT require a PTP master to be present: for a slave, "armed and waiting"
# is the correct state and the network it will join is not ours to check.
# ===========================================================================
FAILED=0
check_ok()   { printf '  [ ok ] %s\n' "$*"; }
check_bad()  { printf '  [FAIL] %s\n' "$*"; FAILED=1; }
check_skip() { printf '  [skip] %s\n' "$*"; }
check_note() { printf '  [note] %s\n' "$*"; }

verify_argv() {  # verify_argv UNIT EXPECTED_ARGV
  local u="$1" want="$2" pid got try
  pid="$(systemctl show -p MainPID --value "$u" 2>/dev/null || true)"
  for try in 1 2 3 4 5 6 7 8 9 10; do
    if [ -n "$pid" ] && [ "$pid" != 0 ] && [ -r "/proc/$pid/cmdline" ]; then
      break
    fi
    sleep 0.5
    pid="$(systemctl show -p MainPID --value "$u" 2>/dev/null || true)"
  done
  if [ -z "$pid" ] || [ "$pid" = 0 ]; then
    check_bad "$u has no main process (MainPID=0)"
    return 0
  fi
  got="$(tr '\0' ' ' <"/proc/$pid/cmdline" | sed 's/  */ /g; s/ *$//')"
  want="$(printf '%s' "$want" | sed 's/  */ /g; s/ *$//')"
  if [ "$got" = "$want" ]; then
    check_ok "$u running as expected (pid $pid)"
  else
    # The failure this catches: systemd handing the role arguments to the
    # daemon as ONE argument, which is what happens if the variable in the unit
    # is written braced (${PTP4L_ARGS}) instead of unbraced.
    check_bad "$u is running the wrong arguments
           want: $want
           got:  $got"
  fi
  return 0
}

do_verify() {
  local want_role="$1" role iface u4l uc2s u a e
  FAILED=0

  role="$(env_get PTP_ROLE || true)"
  iface="$(env_get PTP_IFACE || true)"
  if [ -z "$role" ] || [ -z "$iface" ]; then
    check_bad "no role configured in $ENV_FILE -- run 'timesync install slave' (or 'install master') first"
    printf '\nverify: FAILED\n' >&2
    return 4
  fi

  if [ -n "$want_role" ]; then
    case "$want_role" in 1) want_role=slave ;; 2) want_role=master ;; esac
    if [ "$role" != "$want_role" ]; then
      check_bad "this machine is configured as '$role', but '$want_role' was asked for"
      printf '\nverify: FAILED\n' >&2
      return 4
    fi
  fi

  # The mode comes from the install record, not from the arguments being
  # checked: reading it out of the file under test would make the comparison
  # below agree with whatever that file says.
  TIME_STAMPING="$(stamping_recorded)"

  # Whether GNSS quality is advertised is read off the machine, not off the
  # command line: verify reports what IS, not what was asked for.
  if grep -q '^clockClass' "$(R "$CONF_DIR/ptp4l-$role.conf")" 2>/dev/null; then
    ADVERTISE_GNSS=1
  else
    ADVERTISE_GNSS=0
  fi

  IFACE="$iface"
  role_values "$role"
  u4l="ptp4l@${iface}.service"
  uc2s="phc2sys@${iface}.service"
  printf 'role %s on %s, time stamping %s\n' "$ROLE" "$iface" "$TIME_STAMPING"

  # --- 1. The role file says exactly what this role requires --------------
  local want_args cfg_args conf_transport conf_domain conf_stamping
  want_args="$PTP4L_ARGS"
  cfg_args="$(env_get PTP4L_ARGS || true)"
  if [ "$cfg_args" = "$want_args" ]; then
    check_ok "role file arguments are the canonical ones for role $ROLE"
  else
    check_bad "$ENV_FILE has the wrong arguments for role $ROLE
           want: $want_args
           got:  $cfg_args"
  fi

  conf_transport="$(conf_get "$CONF_DIR/ptp4l-$role.conf" network_transport || true)"
  conf_domain="$(conf_get "$CONF_DIR/ptp4l-$role.conf" domainNumber || true)"
  if [ -n "$conf_transport" ] && [ -n "$conf_domain" ]; then
    check_ok "role config: transport $conf_transport, domain $conf_domain"
    # Only compared when verify was given the flag itself: verify carries no
    # memory of what the install was told, and its own defaults would fail every
    # board that legitimately runs in a non-zero domain.
    if [ "$DOMAIN_SET" = 1 ] && [ "$conf_domain" != "$DOMAIN" ]; then
      check_bad "role config says domain $conf_domain but verify was given --domain $DOMAIN"
    fi
    if [ "$TRANSPORT_SET" = 1 ] && [ "$conf_transport" != "$TRANSPORT" ]; then
      check_bad "role config says transport $conf_transport but verify was given --transport $TRANSPORT"
    fi
  else
    check_bad "$CONF_DIR/ptp4l-$role.conf is missing or has no network_transport/domainNumber"
  fi

  # In software/legacy mode the config must NOT pin the mode: those modes are
  # selected by the flag in PTP4L_ARGS, and a time_stamping line here would be a
  # second, silently-ignorable source for the same decision.
  conf_stamping="$(conf_get "$CONF_DIR/ptp4l-$role.conf" time_stamping || true)"
  if [ -n "$conf_stamping" ]; then
    check_bad "$CONF_DIR/ptp4l-$role.conf sets time_stamping $conf_stamping as well as the mode flag in PTP4L_ARGS -- remove one, they are two answers to one question"
  fi

  # --- 2. Timestamping capability of the interface PTP actually runs on ---
  local caps
  caps="$(ethtool -T "$iface" 2>/dev/null || true)"
  if [ "$TIME_STAMPING" = software ]; then
    # Nothing to require of the NIC: the kernel stamps in CLOCK_REALTIME.  What
    # the NIC reports is printed because it is often the reason a board was
    # expected to work in hardware mode.
    case "$caps" in
      *hardware-transmit*) check_ok "$iface: software time stamping in use (the NIC also advertises hardware timestamping, which is not the same as delivering it)" ;;
      *)                   check_ok "$iface: software time stamping in use (the NIC does not advertise hardware timestamping, which this mode does not need)" ;;
    esac
  else
    case "$caps" in
      *hardware-transmit*hardware-receive*|*hardware-receive*hardware-transmit*)
        check_ok "$iface hardware-timestamps both directions" ;;
      *) check_bad "$iface cannot hardware timestamp, or does not exist, but time stamping is $TIME_STAMPING" ;;
    esac
  fi

  # --- 3. The units this mode needs: up, enabled, right argv --------------
  #
  # In hardware mode that is ptp4l plus phc2sys, because ptp4l's clock is then
  # the NIC's and something has to carry it to CLOCK_REALTIME.  In software and
  # legacy mode ptp4l disciplines CLOCK_REALTIME itself, so phc2sys is not part
  # of the deployment -- and must NOT be running: it would copy a PHC that
  # nothing is steering into the very clock ptp4l is steering, and the two would
  # pull against each other.
  local phc_args units=("$u4l")
  uses_phc2sys && units+=("$uc2s")
  phc_args="$(env_get PHC2SYS_ARGS || true)"
  local u4l_svc="$u4l"
  for u in "${units[@]}"; do
    a="$(systemctl is-active "$u" 2>/dev/null || true)"
    e="$(systemctl is-enabled "$u" 2>/dev/null || true)"
    [ "$a" = active ]  && check_ok "$u active" || check_bad "$u is not active ($a)"
    [ "$e" = enabled ] && check_ok "$u enabled (survives a reboot)" || check_bad "$u is not enabled ($e)"
    if [ "$u" = "$u4l_svc" ]; then
      verify_argv "$u" "/usr/sbin/ptp4l $cfg_args -i $iface"
    else
      verify_argv "$u" "/usr/sbin/phc2sys -w $phc_args"
    fi
    # A past auto-restart is history once the unit is up again -- a board that
    # boots before eth0 has an address restarts ptp4l once and is then perfectly
    # healthy, and failing that board would block a line that has nothing wrong
    # with it.  Being down is what must fail, and that is checked above (inactive
    # or MainPID=0); a live crash loop shows up there, since RestartSec=5 keeps a
    # dying unit in the auto-restart state with no main process.  So a restart
    # count on a unit that is up now is reported, not failed.
    local restarts
    restarts="$(systemctl show -p NRestarts --value "$u" 2>/dev/null || true)"
    if [ "${restarts:-0}" = 0 ]; then
      check_ok "$u has not been restarted"
    elif [ "$a" = active ]; then
      check_note "$u has restarted ${restarts} time(s) since boot but is up now; if that is unexpected see journalctl -u $u -n 50, then 'systemctl reset-failed $u'"
    else
      check_bad "$u has restarted ${restarts} time(s) -- it is failing; see journalctl -u $u -n 50"
    fi
  done

  if ! uses_phc2sys && have_unit "$uc2s"; then
    a="$(systemctl is-active "$uc2s" 2>/dev/null || true)"
    e="$(systemctl is-enabled "$uc2s" 2>/dev/null || true)"
    if [ "$a" = active ] || [ "$e" = enabled ]; then
      check_bad "$uc2s is $a/$e, but time stamping is $TIME_STAMPING: ptp4l is disciplining CLOCK_REALTIME by itself, and phc2sys would fight it over the same clock"
    else
      check_ok "$uc2s is not active or enabled (not needed in $TIME_STAMPING mode)"
    fi
  fi

  # --- 4. Nothing else on this machine is enabled to drive PTP ------------
  local found
  found="$(enabled_instances | tr '\n' ' ')"
  if [ -n "${found// /}" ]; then
    check_bad "other PTP instances are enabled: $found"
  else
    check_ok "no other PTP instance enabled"
  fi

  # --- 5. Exactly one clock daemon owns CLOCK_REALTIME --------------------
  local chrony_active="" other_on="" owner="ptp4l"
  uses_phc2sys && owner="phc2sys"
  for u in $NTP_UNITS; do
    have_unit "$u" || continue
    a="$(systemctl is-active "$u" 2>/dev/null || true)"
    e="$(systemctl is-enabled "$u" 2>/dev/null || true)"
    case " $CHRONY_UNITS " in
      *" $u "*)
        if [ "$a" = active ]; then chrony_active="$u"; fi
        ;;
      *)
        if [ "$a" = active ] || [ "$e" = enabled ]; then other_on="$other_on $u"; fi
        ;;
    esac
  done

  if [ "$ROLE" = slave ]; then
    if [ -n "$chrony_active" ] || [ -n "$other_on" ]; then
      check_bad "a clock daemon is still active or enabled:${chrony_active:+ $chrony_active}${other_on} -- it would fight $owner over CLOCK_REALTIME"
    else
      check_ok "no other clock daemon active or enabled ($owner owns CLOCK_REALTIME)"
    fi
  else
    if [ -n "$chrony_active" ]; then
      check_ok "$chrony_active active (disciplining CLOCK_REALTIME for this master)"
    else
      check_bad "no chrony unit is active -- the master role has no disciplined time source"
    fi
    if [ -n "$other_on" ]; then
      check_bad "another clock daemon is active or enabled:$other_on -- it would fight chrony"
    fi
  fi

  # --- 6. The running ptp4l really uses the clock the mode claims ---------
  #
  # Read off the live process -- the set of /dev/ptp* files it holds open --
  # because that is the one signal that is true whatever the flags and the
  # config say.  ptp4l opens the PHC (and keeps the fd) only when it stamps in
  # hardware; in software and legacy mode it holds no ptp device at all and
  # drives CLOCK_REALTIME directly.  The journal is checked too, in hardware
  # mode only, because that is the only mode that has a "selected /dev/ptpN as
  # PTP clock" line to look for.
  #
  # The journal window is scoped to the current boot (-b) and the most recent
  # match is taken.  Both matter for a ship gate: without -b this was observed
  # citing "[3480.254] selected /dev/ptp0", an uptime belonging to the
  # *previous* boot, and `grep -m1` took the oldest line of the window, so a
  # unit that had restarted reported evidence from a run that has since exited
  # rather than the one on the line right now.
  local pid nptp log line
  pid="$(systemctl show -p MainPID --value "$u4l" 2>/dev/null || true)"
  if [ -z "$pid" ] || [ "$pid" = 0 ]; then
    check_skip "$u4l has no main process, so the clock it opened cannot be checked"
  else
    nptp="$(ls -l "/proc/$pid/fd" 2>/dev/null | grep -c '/dev/ptp' || true)"
    if [ "$TIME_STAMPING" = hardware ]; then
      if [ "${nptp:-0}" -gt 0 ]; then
        check_ok "ptp4l holds the NIC clock open (/proc/$pid/fd -> /dev/ptp*)"
      else
        check_bad "time stamping is hardware but ptp4l (pid $pid) holds no /dev/ptp* descriptor -- the NIC clock is not what it is using"
      fi
      log="$(journalctl -b -u "$u4l" --no-pager -o cat -n 200 2>/dev/null || true)"
      if [ -z "$log" ]; then
        check_skip "journal for $u4l is empty or unreadable; cannot confirm the NIC clock was bound"
      else
        line="$(printf '%s\n' "$log" | grep 'selected /dev/ptp' | tail -n 1 || true)"
        if [ -n "$line" ]; then
          check_ok "ptp4l bound the NIC clock: $line"
        else
          check_bad "no 'selected /dev/ptpN as PTP clock' in the last 200 journal lines of $u4l this boot -- hardware timestamping may not be in use"
        fi
      fi
    else
      if [ "${nptp:-0}" -eq 0 ]; then
        check_ok "ptp4l stamps in CLOCK_REALTIME, not in a NIC clock (pid $pid holds no /dev/ptp* descriptor, as $TIME_STAMPING mode requires)"
      else
        check_bad "time stamping is $TIME_STAMPING but ptp4l (pid $pid) holds $nptp /dev/ptp* descriptor(s) -- this machine is not running the mode it is recorded as"
      fi
    fi
  fi

  # --- 7. master: is this board actually a GNSS grandmaster? --------------
  if [ "$ROLE" = master ]; then
    if ! gps_ready; then
      printf '  [GPS ] no GNSS reference is configured on this board\n'
      printf '\nverify: GPS UNCONFIGURED -- this unit multiplies system time, not satellite\n        time.  Do NOT ship it as a grandmaster.\n' >&2
      return 5
    fi
    check_ok "GNSS reference recipe present ($REFCLOCK_DEST)"

    if [ "$ADVERTISE_GNSS" != 1 ]; then
      check_bad "a GNSS reference is configured but the time quality is not advertised in $CONF_DIR/ptp4l-$role.conf; every slave would see 'not a reference' and refuse to lock onto this master.  Reinstall with --advertise-gnss-quality"
    else
      check_ok "grandmaster time quality advertised (clockClass 6 / accuracy 0x21 / GNSS)"
    fi

    if command -v chronyc >/dev/null 2>&1; then
      local srcs
      srcs="$(chronyc sources 2>/dev/null || true)"
      if printf '%s' "$srcs" | grep -q '^#'; then
        check_ok "chrony has a refclock source registered"
      elif [ -z "$srcs" ]; then
        check_skip "chronyc returned nothing; cannot confirm the refclock is registered"
      else
        check_bad "chrony lists no refclock source -- check 'chronyc sources', the receiver's wiring, and its sky view"
      fi
    fi
  fi

  if [ "$FAILED" != 0 ]; then
    printf '\nverify: FAILED\n' >&2
    return 4
  fi
  printf '\nverify: OK -- this unit is fit to ship in role %s\n' "$ROLE"
  return 0
}

# ===========================================================================
# Status
# ===========================================================================
do_status() {
  local iface role u4l uc2s stamp phc_args
  iface="$(env_get PTP_IFACE || true)"
  role="$(env_get PTP_ROLE || true)"
  iface="${iface:-$DEFAULT_IFACE}"
  u4l="ptp4l@${iface}.service"
  uc2s="phc2sys@${iface}.service"
  stamp="$(stamping_recorded)"
  phc_args="$(env_get PHC2SYS_ARGS || true)"

  printf 'Configuration (%s)\n' "$ENV_FILE"
  printf '  %-16s %s\n' role "${role:-(unset -- run: timesync slave|master)}"
  printf '  %-16s %s\n' interface "$iface"
  printf '  %-16s %s\n' 'time stamping' "$(case "$stamp" in
      software) printf 'software (kernel, in CLOCK_REALTIME -- no NIC clock involved)' ;;
      legacy)   printf 'legacy (CLOCK_REALTIME; needs NIC support this board may refuse)' ;;
      hardware) printf 'hardware (NIC clock, carried to CLOCK_REALTIME by phc2sys)' ;;
      *)        printf '(none -- nothing is installed here)' ;;
    esac)"
  printf '  %-16s %s\n' 'ptp4l args' "$(env_get PTP4L_ARGS || echo '(unset)')"
  if [ -n "$phc_args" ]; then
    printf '  %-16s %s\n' 'phc2sys args' "$phc_args"
  elif [ -n "$stamp" ]; then
    printf '  %-16s %s\n' 'phc2sys args' "(none -- not used in $stamp mode)"
  else
    printf '  %-16s %s\n' 'phc2sys args' '(none)'
  fi
  printf '  %-16s %s\n' provisioned "by timesync $(state_get tool_version || echo '(unknown)') on $(state_get installed || echo '(unknown)')"

  printf '\nLive state\n'
  printf '  %-16s %s\n' "$u4l" "$(unit_state "$u4l")"
  printf '  %-16s %s\n' "$uc2s" "$(unit_state "$uc2s")"
  printf '  %-16s %s\n' chrony.service "$(unit_state chrony.service)"

  if [ "$role" = master ]; then
    if gps_ready; then
      printf '\nGNSS reference: %s\n' "$REFCLOCK_DEST"
    else
      printf '\nNOTE: the master role is a skeleton right now -- no GNSS reference\n'
      printf '      is configured, so this board is multiplying system time, not\n'
      printf '      satellite time.\n'
    fi
  fi

  printf '\nRecent ptp4l output.  A "master offset" line roughly once a second\n'
  printf 'means it is locked to a master; silence means none has been heard:\n'
  journalctl -u "$u4l" -n 6 --no-pager -o cat 2>/dev/null | sed 's/^/  /' || true

  printf '\nSystem clock now: %s\n' "$(date -Is)"
}

# ===========================================================================
# Commands
# ===========================================================================
write_install_files() {  # writes every generated file; sets RESTART_NEEDED
  CHANGED=0
  # One self-contained file per role -- shared settings, then the role's own,
  # then the GNSS quality lines when they apply.  All three fragments are
  # concatenated, and each keeps its own [global] header: keys accumulate
  # within one file, including across two [global] sections.
  install_tpl_join "$CONF_DIR/ptp4l-slave.conf" tpl_common_conf tpl_slave_conf
  if [ "$ROLE" = master ] && [ "$ADVERTISE_GNSS" = 1 ]; then
    install_tpl_join "$CONF_DIR/ptp4l-master.conf" tpl_common_conf tpl_master_conf tpl_grandmaster_conf
  else
    install_tpl_join "$CONF_DIR/ptp4l-master.conf" tpl_common_conf tpl_master_conf
  fi
  install_tpl tpl_ptp4l_unit   "$UNIT_DIR/ptp4l@.service"
  install_tpl tpl_phc2sys_unit "$UNIT_DIR/phc2sys@.service"

  # The two files an earlier version split this into.  Neither is named in
  # PTP4L_ARGS any more, so leaving them behind would leave settings on disk
  # that nothing reads -- the trap this layout exists to avoid.
  remove_generated "$CONF_DIR/ptp4l-common.conf"
  remove_generated "$CONF_DIR/ptp4l-grandmaster.conf"

  # Decided after every write, the GNSS lines included: they are part of the
  # file ptp4l reads, and only a restart makes systemd re-read the
  # EnvironmentFile, so deciding earlier would leave a daemon running with the
  # arguments it was started with while the file it reads has changed.
  if [ "$CHANGED" = 1 ]; then
    RESTART_NEEDED=1
  fi

  if [ -n "$REFCLOCK_FILE" ]; then
    # The marker line goes on top of the integrator's recipe, where chrony
    # treats it as a comment.  It is what makes ownership of the file -- and so
    # its removal on uninstall -- unambiguous.
    install_marked_copy "$REFCLOCK_FILE" "$REFCLOCK_DEST"
  elif [ "$KEEP_GNSS" != 1 ]; then
    # No recipe given and this is not a switch, so it is a full re-provision to
    # a role that does not consume GNSS: drop a recipe left over from an
    # earlier GNSS install, so what is on disk describes this board's actual
    # wiring.  A `switch` deliberately keeps it -- switching back to master
    # has to find the recipe still there.
    remove_generated "$REFCLOCK_DEST"
  fi

  local self
  self="$(readlink -f "${BASH_SOURCE[0]}" 2>/dev/null || true)"
  if [ -n "$self" ] && [ -r "$self" ]; then
    install_from_file "$self" "$TOOL_DEST" 0755
  else
    warn "cannot resolve my own path; skipping the install of $TOOL_DEST"
  fi
  return 0
}

daemon_reload_if_needed() {
  if [ "$DRY" = 1 ]; then
    say "would run systemctl daemon-reload"
    return 0
  fi
  systemctl daemon-reload
}

do_install() {
  local role_arg="$1"

  ROLE_ARG="$role_arg"

  if [ -z "$ROOT" ]; then
    apt_ensure            # first: interface detection needs ethtool
  else
    say "--root $ROOT: staging only; apt, systemctl and hardware checks are skipped"
  fi

  resolve_iface
  role_values "$role_arg"
  preflight_args
  if [ -z "$ROOT" ]; then
    preflight_machine
  fi

  say "installing role $ROLE on $IFACE"
  write_install_files

  if [ -n "$ROOT" ]; then
    install_tpl tpl_env_file "$ENV_FILE"
    write_state
    printf '\n'
    say "staged under $ROOT; nothing on this machine was changed"
    return 0
  fi

  if [ "$RESTART_NEEDED" = 1 ]; then
    daemon_reload_if_needed
  fi

  role_values "$role_arg"
  apply_role
  write_state

  if [ "$DRY" = 1 ]; then
    printf '\n'
    say "dry run: nothing was changed, so there is nothing to verify"
    return 0
  fi

  if [ "$NO_VERIFY" = 1 ]; then
    printf '\n'
    warn "--no-verify was given: the apply steps ran, but this unit has NOT been checked"
    return 0
  fi

  printf '\n'
  do_verify "$role_arg"
}

do_switch() {
  local role_arg="$1"

  if [ ! -r "$ENV_FILE" ] || [ ! -r "$TOOL_DEST" ] \
     || [ ! -r "$UNIT_DIR/ptp4l@.service" ] || [ ! -r "$CONF_DIR/ptp4l-slave.conf" ]; then
    die 2 "this machine has not been provisioned yet -- run 'timesync install slave' (or 'install master') first"
  fi

  ROLE_ARG="$role_arg"
  KEEP_GNSS=1

  # A switch changes the ROLE and nothing else.  Everything else the machine
  # was already doing -- the interface it runs on, the transport and domain it
  # was installed with, whether it advertises GNSS quality -- carries over
  # unless it is given explicitly.  Switching must never quietly reset the
  # domain or demote a GNSS grandmaster to a skeleton.
  #
  # GNSS quality is the exception: it is a master-only attribute, and carrying
  # it into slave makes preflight_args reject the very switch back to slave
  # ("--advertise-gnss-quality is master only"), which would strand a board that
  # was serving GNSS.  So it is carried forward only when the target role is
  # master; the intent survives in the state file either way, and the next
  # switch to master picks it up again.
  local prev
  case "$role_arg" in
    master)
      if [ "$ADVERTISE_SET" != 1 ]; then
        prev="$(state_get gnss_quality || true)"
        if [ "${prev:-0}" = 1 ]; then
          ADVERTISE_GNSS=1
          note "keeping GNSS time-quality advertising from the existing install"
        fi
      fi
      ;;
  esac
  if [ "$DOMAIN_SET" != 1 ]; then
    prev="$(state_get domain || true)"
    if [ -n "$prev" ] && [ "$prev" != "$DOMAIN" ]; then
      DOMAIN="$prev"
      note "keeping PTP domain $DOMAIN from the existing install"
    fi
  fi
  if [ "$TRANSPORT_SET" != 1 ]; then
    prev="$(state_get transport || true)"
    if [ -n "$prev" ] && [ "$prev" != "$TRANSPORT" ]; then
      TRANSPORT="$prev"
      note "keeping transport $TRANSPORT from the existing install"
    fi
  fi
  # Time stamping carries over like the rest, and it decides which units the
  # new role needs -- so it has to be settled before role_values() is called.
  if [ "$TIME_STAMPING_SET" != 1 ]; then
    prev="$(stamping_recorded)"
    if [ -n "$prev" ] && [ "$prev" != "$TIME_STAMPING" ]; then
      TIME_STAMPING="$prev"
      note "keeping time stamping $TIME_STAMPING from the existing install"
    fi
  fi

  resolve_iface
  role_values "$role_arg"
  preflight_args
  preflight_machine

  # The role-dependent config files have to be (re)written here, not only by
  # `install`.  Switching to a GNSS master adds the clockClass/clockAccuracy
  # lines to the master file, and switching away removes them -- a board left
  # advertising GNSS quality it is no longer fed would be lying to every slave.
  # This also makes --domain/--transport on a switch actually take effect, and
  # keeps the unit files honest if one of them was edited by hand.  Everything
  # already correct reports "unchanged".
  write_install_files
  if [ "$RESTART_NEEDED" = 1 ]; then
    daemon_reload_if_needed
  fi
  role_values "$role_arg"      # write_install_files may have moved the target

  apply_role
  write_state

  if [ "$DRY" = 1 ]; then
    printf '\n'
    say "dry run: nothing was changed, so there is nothing to verify"
    return 0
  fi

  if [ "$NO_VERIFY" = 1 ]; then
    return 0
  fi
  printf '\n'
  do_verify "$role_arg"
}

do_uninstall() {
  local u found

  if [ -n "$ROOT" ]; then
    say "--root $ROOT: removing only the staged tree; systemd is not touched"
  else
    [ "$(id -u)" -eq 0 ] || die 2 "must run as root (try: sudo $0 uninstall)"
    # IFACE, not a local: enabled_instances() excludes the configured instance
    # by comparing against $IFACE, so leaving it empty here made the two real
    # units look like strays and reported each of them twice.
    IFACE="$(env_get PTP_IFACE || true)"
    IFACE="${IFACE:-$DEFAULT_IFACE}"
    found="$(enabled_instances | tr '\n' ' ')"
    if [ "$DRY" = 1 ]; then
      for u in "ptp4l@${IFACE}.service" "phc2sys@${IFACE}.service" $found; do
        say "would stop and disable $u"
      done
    else
      # The configured units may not be there to begin with (never installed,
      # or a previous uninstall already removed them).  The strays in $found
      # are enable symlinks by construction, so those are removed even when the
      # template behind them has been deleted -- a dangling symlink is exactly
      # the leftover this tool exists to clean up.
      for u in "ptp4l@${IFACE}.service" "phc2sys@${IFACE}.service"; do
        have_unit "$u" || continue
        act "stop and disable $u"
        systemctl disable --now "$u" >/dev/null 2>&1 || true
      done
      for u in $found; do
        act "stop and disable $u"
        systemctl disable --now "$u" >/dev/null 2>&1 || true
      done
    fi
  fi

  remove_generated "$UNIT_DIR/ptp4l@.service"
  remove_generated "$UNIT_DIR/phc2sys@.service"
  remove_generated "$CONF_DIR/ptp4l-common.conf"
  remove_generated "$CONF_DIR/ptp4l-slave.conf"
  remove_generated "$CONF_DIR/ptp4l-master.conf"
  remove_generated "$CONF_DIR/ptp4l-grandmaster.conf"
  remove_generated "$ENV_FILE"
  remove_generated "$REFCLOCK_DEST"
  # The installed copy of this script leads with a shebang, so it cannot also
  # lead with the marker; it is recognised by a phrase from its own header.
  remove_generated "$TOOL_DEST" 'time_synchronization_installer -- deploy and switch'
  remove_generated "$STATE_FILE"

  # Put back whatever clock daemon this installation turned off.
  local path
  path="$(R "$DISABLED_NTP_FILE")"
  if [ -s "$path" ]; then
    while read -r u; do
      case "$u" in '' | '#'*) continue ;; esac
      say "re-enabling $u (it was enabled before this install)"
      if [ "$DRY" != 1 ]; then systemctl enable --now "$u" >/dev/null 2>&1 || true; fi
    done <"$path"
  fi
  remove_generated "$DISABLED_NTP_FILE"
  if [ "$DRY" != 1 ]; then rmdir "$(R "$STATE_DIR")" 2>/dev/null || true; fi

  if [ "$DRY" != 1 ] && [ -z "$ROOT" ]; then
    systemctl daemon-reload
  fi

  printf '\n'
  say "uninstalled -- the linuxptp package itself is untouched"
  note "the units that ship in /lib/systemd/system/ are in effect again"
}

# ===========================================================================
# Argument parsing
# ===========================================================================
while [ $# -gt 0 ]; do
  case "$1" in
    install|switch|uninstall)
      [ -z "$CMD" ] || die 1 "more than one command given ('$CMD' and '$1')"
      CMD="$1"; shift ;;
    status|verify)
      [ -z "$CMD" ] || die 1 "more than one command given ('$CMD' and '$1')"
      CMD="$1"; shift ;;
    slave|master)
      # `slave` and `master` are the way to spell the role, and what the word
      # means depends on what came before it: after a command that takes a role
      # it IS that role (`install slave`), while on its own it is the `switch`
      # shorthand (`timesync master` == `timesync switch master`).
      case "$CMD" in
        install|switch|verify)
          [ -z "$ROLE_ARG" ] || die 1 "role given twice ('$ROLE_ARG' and '$1')"
          ROLE_ARG="$1"; shift ;;
        "")
          CMD="$1"; shift ;;
        *)
          die 1 "'$CMD' does not take a role" ;;
      esac ;;
    wait-iface)
      [ -z "$CMD" ] || die 1 "more than one command given ('$CMD' and '$1')"
      [ $# -ge 2 ] || die 1 "wait-iface needs an interface name (usage: $NAME wait-iface <iface> [seconds])"
      # This command takes a positional argument, so a mistyped option would be
      # swallowed as the interface name and then wait uselessly for 30s.
      case "$2" in
        -*) die 1 "wait-iface: '$2' looks like an option; usage: $NAME wait-iface <iface> [seconds]" ;;
      esac
      CMD="$1"; WAIT_IFACE="$2"
      # Optional third word is the timeout in seconds.
      if [ $# -ge 3 ]; then
        case "$3" in
          '' | *[!0-9]*) die 1 "wait-iface: timeout must be a whole number of seconds, got '$3'" ;;
        esac
        WAIT_TIMEOUT="$3"; shift 3
      else
        shift 2
      fi ;;
    1|2)
      # Kept as shorthands for `slave` and `master`.  Digits never stand in for
      # a command, though: `timesync 1` was refused before this, and quietly
      # turning it into a state-changing switch is a worse answer to a typo
      # than refusing is.
      [ -z "$ROLE_ARG" ] || die 1 "role given twice ('$ROLE_ARG' and '$1')"
      # Normalised before anything can report an error, so that every message --
      # including the refusals just below -- prints the word rather than the
      # digit.  The digit is the spelling people found hard to follow.
      case "$1" in 1) ROLE_ARG=slave ;; 2) ROLE_ARG=master ;; esac
      case "$CMD" in
        install|switch|verify) ;;
        "") die 1 "role '$ROLE_ARG' needs a command: install $ROLE_ARG | switch $ROLE_ARG" ;;
        *)  die 1 "'$CMD' does not take a role" ;;
      esac
      shift ;;
    [0-9]*)
      die 1 "unknown role '$1' (want: slave | master, or 1 | 2)" ;;
    --iface)         [ $# -ge 2 ] || die 1 "--iface needs a value"; IFACE_OPT="$2"; shift 2 ;;
    --domain)        [ $# -ge 2 ] || die 1 "--domain needs a value"; DOMAIN="$2"; DOMAIN_SET=1; shift 2 ;;
    --transport)     [ $# -ge 2 ] || die 1 "--transport needs a value"; TRANSPORT="$2"; TRANSPORT_SET=1; shift 2 ;;
    --time-stamping) [ $# -ge 2 ] || die 1 "--time-stamping needs a value (software | hardware | legacy)"; TIME_STAMPING="$2"; TIME_STAMPING_SET=1; shift 2 ;;
    --refclock-file) [ $# -ge 2 ] || die 1 "--refclock-file needs a value"; REFCLOCK_FILE="$2"; shift 2 ;;
    --gps-device)    [ $# -ge 2 ] || die 1 "--gps-device needs a value"; GPS_DEVICE="$2"; shift 2 ;;
    --root)          [ $# -ge 2 ] || die 1 "--root needs a value"; ROOT="${2%/}"; shift 2 ;;
    --advertise-gnss-quality) ADVERTISE_GNSS=1; ADVERTISE_SET=1; shift ;;
    --no-apt)        NO_APT=1; shift ;;
    --no-verify)     NO_VERIFY=1; shift ;;
    --force)         FORCE=1; shift ;;
    --dry-run)       DRY=1; shift ;;
    -h|--help)       usage; exit 0 ;;
    -V|--version)    printf 'timesync %s\n' "$VERSION"; exit 0 ;;
    --)              shift; break ;;
    *)               usage; die 1 "unknown argument '$1'" ;;
  esac
done

case "$CMD" in
  install|switch)
    # ROLE_ARG is always the word by now -- the parser translates 1/2 on the
    # way in -- so there is no digit case to allow for here.
    case "$ROLE_ARG" in
      slave|master) ;;
      "") die 1 "$CMD needs a role: $CMD slave | $CMD master" ;;
      *)  die 1 "unknown role '$ROLE_ARG' (want: slave | master)" ;;
    esac
    if [ -n "$ROOT" ] && [ "$CMD" = switch ]; then
      die 1 "--root is for install and uninstall only; switch changes a live machine"
    fi
    ;;
  verify)
    if [ -n "$ROOT" ]; then
      die 1 "--root is for install and uninstall only; verify inspects a live machine"
    fi
    ;;
esac

case "$CMD" in
  install)   do_install "$ROLE_ARG" ;;
  switch)    do_switch "$ROLE_ARG" ;;
  slave)     do_switch slave ;;
  master)    do_switch master ;;
  status)    do_status ;;
  verify)    do_verify "${ROLE_ARG:-}" ;;
  wait-iface) do_wait_iface "$WAIT_IFACE" "${WAIT_TIMEOUT:-30}" ;;
  uninstall) do_uninstall ;;
  *)         usage; exit 2 ;;
esac
